export interface Property {
  id: string;
  name: string;
  description: string;
}

export const PROPERTIES: Property[] = [
  { id: 'P1', name: 'Latency Bound', description: 'Strict delivery time bounds (e.g. 300ms p90) required for BFT consensus.' },
  { id: 'P2', name: 'Bandwidth Overhead', description: 'Additional data traffic generated by the privacy mechanism.' },
  { id: 'P3', name: 'Identity Unlinkability', description: 'Severing the link between physical IP address and validator identity.' },
  { id: 'P4', name: 'Sybil Resistance', description: 'Resistance against adversaries spinning up many identities to eclipse nodes.' },
  { id: 'P5', name: 'GPA Resistance', description: 'Protection against Global Passive Adversaries monitoring traffic profiles.' },
  { id: 'P6', name: 'BFT Compatibility', description: 'How well the mechanism fits within Ethereum\'s consensus slot rhythms.' },
  { id: 'P7', name: 'Implementation Complexity', description: 'Amount of new networking machinery and spec changes required.' },
  { id: 'P8', name: 'Economic Deterrence', description: 'Using financial slashing to disincentivize malicious behavior.' },
];
