export interface Property {
  id: string;
  name: string;
  description: string;
  refs?: string[];
}

export const PROPERTIES: Property[] = [
  { id: 'P1', name: 'Latency Bound', description: 'Strict delivery time bounds (e.g. 300ms p90) required for BFT consensus.' },
  { id: 'P2', name: 'Bandwidth Overhead', description: 'Additional data traffic generated by the privacy mechanism.' },
  { 
    id: 'P3', 
    name: 'Identity Unlinkability', 
    description: 'Severing the link between physical IP address and validator identity. Based on the foundational concept that items of interest (subjects, messages, actions) are unlinkable if an attacker cannot distinguish whether they are related or not.',
    refs: [
      '[Anonymity, Unlinkability, Undetectability, and Unobservability: A Proposal for Terminology (v0.34)](https://www.maroki.de/pub/verschiedenes/2010_Anon_Terminology_v0.34.pdf)'
    ]
  },
  { id: 'P4', name: 'Sybil Resistance', description: 'Resistance against adversaries spinning up many identities to eclipse nodes.' },
  { 
    id: 'P5', 
    name: 'GPA Resistance', 
    description: 'Protection against Global Passive Adversaries monitoring traffic profiles. Aims for Unobservability, where an attacker cannot distinguish whether an item of interest exists, and subjects remain anonymous even if items were detectable.',
    refs: [
      '[Anonymity, Unlinkability, Undetectability, and Unobservability: A Proposal for Terminology (v0.34)](https://www.maroki.de/pub/verschiedenes/2010_Anon_Terminology_v0.34.pdf)'
    ]
  },
  { id: 'P6', name: 'BFT Compatibility', description: 'How well the mechanism fits within Ethereum\'s consensus slot rhythms.' },
  { id: 'P7', name: 'Implementation Complexity', description: 'Amount of new networking machinery and spec changes required.' },
  { id: 'P8', name: 'Economic Deterrence', description: 'Using financial slashing to disincentivize malicious behavior.' },
  { id: 'P9', name: 'Censorship Resilience', description: 'The mathematical guarantee against the deterministic exclusion of honest votes or messages by a subset of malicious nodes.' },
];
